config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'main/show_video/:id', to: 'main#show_video', as: 'show_video'
  post 'main/ask_question'

  resources :videos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :video_file
  has_one_attached :preview_file

  validates :video_type, presence: true
  validates :title, presence: true
  # validates :description, presence: true

  validate :video_validate
  validate :preview_validate

  enum video_type: [ 'Реклама', 'Торжества', 'Семейное']

  def video_validate
    if !video_file.attached? && !vimeo_url.present?
      errors.add(:video_file, 'Нужно добавить видео файл');
    end
  end

  def preview_validate
    if !preview_file.attached?
      errors.add(:preview_file, 'Нужно добавить файл превью');
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :video_preview

  private
  def video_preview video
    if video.preview_file.attached? then video.preview_file else video.video_file.preview(resize: "500x500") end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def show_video
    @video = Video.find(params[:id])
  end

  def ask_question
    AskMailMailer.with(sender: params[:sender]).ask_mail.deliver_now
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  http_basic_authenticate_with name: "eco369", password: "369369369"
  layout 'admin'

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    if @video.save
      flash[:success] = 'Видео успешно создано'
      redirect_to videos_path
    else
      render 'new'
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)

    if @video.save
      flash[:success] = 'Видео успешно изменено'
      redirect_to videos_path
    else
      render 'edit'
    end
  end

  def destroy
    Video.find(params[:id]).destroy
  end

  private
  def video_params
    params.require(:video).permit(:video_type, :title, :description, :video_file, :preview_file, :vimeo_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_ask_form.html.erb
<div class="contact-form">
  <div class="side bg-danger">
    <span class="ask">Задать вопрос</span>
    <i class="close-ask far fa-times-circle "></i>
  </div>
  <%= form_with :scope => :sender, :url => main_ask_question_path do |form| %>
    <%= form.label 'Ваше имя' %>
    <%= form.text_field :fname, required: true %>

    <%= form.label 'Ваша почта' %>
    <%= form.email_field :email, required: true%>

    <%= form.label 'Ваш вопрос' %>
    <%= form.text_area :body, required: true %>

    <%= form.submit 'Отправить', class: 'send-button', data: { disable_with: 'Отправка...' } %>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>

  <body>
    <div class="container pt-4">
      <% if flash.any? %>
        <% flash.each do |key, message| %>
          <div class="alert alert-<%= key %>" role="alert">
            <%= message %>
          </div>
        <% end %>
      <% end %>
      <div id="errors-block"></div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://vjs.zencdn.net/7.5.5/video-js.css" rel="stylesheet">
    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>

  <body>
    <div id="notify"></div>
    <div id="body-overlay" class="d-none"></div>
    <div id="modal" class="d-none">
      <div class="content"></div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/main/_video_modal.html.erb
<div class="cross-side">
  <i class="far fa-times-circle"></i>
</div>
<video id='my-video' class='video-js w-100' controls autoplay preload='auto'
  poster='MY_VIDEO_POSTER.jpg' data-setup='{}'>
    <source src='<%= url_for(video.video_file) %>' type='video/mp4'>
  </video>
<p class="mt-3"><%= video.description %></p>

app/views/main/ask_question.js.erb
$('.contact-form').removeClass('active');
$('.contact-form input').val('');
$('.contact-form textarea').val('');

showNotify('Сообщение отправлено');

app/views/main/index.html.erb
<%= render partial: 'layouts/ask_form' %>

<section id="head-section">
  <div class="img-wrap">
    <div class="container text-center">
      <div class="logo-wrap text-light">
        <div class="pics">
          <img class="preshow" src="<%= image_path 'logo6.png' %>">
          <img class="preshow roll" src="<%= image_path 'logo5.png' %>">
          <img class="preshow roll" src="<%= image_path 'logo4.png' %>">
          <img class="preshow roll" src="<%= image_path 'logo3.png' %>">
          <img class="preshow roll" src="<%= image_path 'logo2.png' %>">
          <img class="preshow roll last" src="<%= image_path 'logo1.png' %>">
        </div>
        <span class="text-uppercase ml-2">
          <span class="ltr preshow">v</span>
          <span class="ltr preshow">i</span>
          <span class="ltr preshow">d</span>
          <span class="ltr preshow">e</span>
          <span class="ltr preshow">o</span>
        </span>
        <span class="ltr">&#160;</span>
        <span class="ltr preshow">д</span>
        <span class="ltr preshow">л</span>
        <span class="ltr preshow">я</span>
        <span class="ltr">&#160;</span>
        <span class="text-uppercase">
          <span class="ltr preshow">в</span>
          <span class="ltr preshow">а</span>
          <span class="ltr preshow">с</span>
        </span>
      </div>
      <h1 class="text-light mt-2 display-4 title">Заказать видеоролик</h1>
      <a href="tel:++79250532139" class="btn btn-danger text-light mt-3 call-button"><i class="fas fa-phone mr-2"></i> +7 (925) 053-21-39</a>
      <div class="align-center">
        <a target="_blank" href="https://www.instagram.com/anatolii_zorin" class="mt-4 d-inline-block bg-light rounded-circle inst text-center">
          <i class="fab fa-instagram text-dark"></i>
        </a>
        <%= image_tag(image_path('inst-letters.png'), :class => 'inst-letters') %>
      </div>
    </div>
  </div>
</section>

<section id="videos-section" class="py-4">
  <div class="container">
    <div class="row">
      <% Video.video_types.keys.each do |type| %>
        <div class="col-4">
          <h4 class="title"><%= type %></h4>
          <% Video.where(video_type: type).each_with_index do |video, index| %>
            <div class="video-item <%= (index > 0 ? 'preshow' : '') %> bg-light mb-5">
              <h6><%= video.title %></h6>
              <div class="image" style="background-image: url(<%= url_for(video_preview(video)) %>)"></div>
              <% if video.vimeo_url.present? %>
                <%= link_to video.vimeo_url, class: 'play-overlay' do %>
                  <i class="fas fa-play-circle"></i>
                <% end %>
              <% else %>
                <%= link_to show_video_path(video), class: 'play-overlay', remote: true, method: :get do %>
                  <i class="fas fa-play-circle"></i>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/main/show_video.js.erb
showModal('<%= j render partial: 'video_modal', locals: { video: @video } %>');

app/views/videos/_errors.html.erb
<div class="alert alert-danger" role="alert">
  <%= message %>
</div>

app/views/videos/_errors.js.erb
var errors = new Array();

<% record.errors.full_messages.each do |message| %>
  errors.push('<%= j render partial: 'errors.html.erb', locals: { message: message } %>');
<% end %>

$('#errors-block').empty();
$('#errors-block').append(errors);

app/views/videos/_form.html.erb
<%= link_to 'На главную', videos_path, class: 'btn btn-primary mb-3' %>

<% @video.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
<% end %>

<%= form_with model: @video, local: true do |form| %>
  <div class="form-group">
    <%= form.label 'Категория видео' %>
    <%= form.select :video_type, Video.video_types.keys, {}, { class: 'form-control ml-3 d-inline-block w-25' } %>
  </div>
  <div class="form-group">
    <%= form.label 'Заголовок' %>
    <%= form.text_field :title, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= form.label 'Описание' %>
    <%= form.text_area :description, rows: 4, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label 'Ссылка на Vimeo' %>
    <%= form.text_field :vimeo_url, class: 'form-control' %>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label 'Видео' %>
        <% if @video.video_file.attached? %>
          <%= video_tag url_for(@video.video_file), controls: true, class: 'w-100 mb-3 rounded' %>
        <% end %>
        <%= form.file_field :video_file, accept: 'video/*', class: 'd-block', required: true, direct_upload: true %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label 'Превью' %>
        <%= puts @video.preview_file %>
        <% if @video.preview_file.attached? %>
          <%= image_tag @video.preview_file, class: 'w-100 mb-3 rounded' %>
        <% end %>
        <%= form.file_field :preview_file, accept: 'image/*', class: 'd-block', required: true, direct_upload: true %>
      </div>
    </div>
  </div>
  <%= form.submit (if action_name == 'new' then 'Добавить видео' elsif action_name == 'edit' then 'Сохранить изменения' end), class: 'btn btn-primary', data: { disable_with: 'Выполнениe...' } %>
<% end %>

app/views/videos/destroy.js.erb
$('.video-card[video-id=<%= params[:id] %>]').remove()

app/views/videos/edit.html.erb
<%= render partial: 'form' %>

app/views/videos/index.html.erb
<%= link_to 'Создать видео', new_video_path, class: 'btn btn-primary' %>

<div class="row">
  <% @videos.each do |video| %>
    <div class="col-sm-4 video-card" video-id="<%= video.id %>">
      <div class="card mt-3">
        <%= image_tag (if video.preview_file.attached? then video.preview_file else video.video_file.preview(resize: '500x500').processed end), class: 'd-block w-100 card-img-top' %>
        <div class="card-body">
          <h5 class="card-title"><%= video.title %></h5>
          <p class="card-text"><%= video.description.length > 50 ? video.description[0...50] + '...' : video.description %></p>
          <p class="card-text text-muted"><%= video.video_type %></p>
          <%= link_to 'Изменить', edit_video_path(video), class: 'btn btn-primary mr-2' %>
          <%= button_to 'Удалить', video_path(video), remote: true, class: 'btn btn-danger', form_class: 'd-inline-block', method: 'delete', data: { confirm: 'Удалить видео?', disable_with: 'Удаление...' } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/videos/new.html.erb
<%= render partial: 'form' %>